### ISSUE TITLE
AC300: Version up to 0.0.23 Incorrect values and batteries are not recognized.

### ISSUE THREAD

**Issue by sibelle-labs** [Patrick762/hassio-bluetti-bt#101]
### What happened?

Hi Patrick !
my 2 cent's debug on ac300 with version 0.0.23

1) no data for total_battery_voltage.
on logs showing ...

2024-05-21 21:42:47.141 WARNING (MainThread) [custom_components.bluetti_bt.sensor] No data for available for (total_battery_voltage)

2) battery packs not detected..
on logs showing ...

2024-05-22 21:26:51.842 DEBUG (MainThread) [custom_components.bluetti_bt.bluetti_bt_lib.bluetooth.device_reader] Parsed pack_num(None) does not match expected '4'

![grafik](https://github.com/Patrick762/hassio-bluetti-bt/assets/65012538/9940867a-ed84-421d-b3c6-3efffa285cd2)

How can i help you ?
Thanks a lot
Cheers

### Version

0.0.23

### What device are you seeing the problem on?

AC300

### What bluetooth connection are you using?

ESPHome bluetooth proxy

### Have you changed the integration settings?

false

**Comment by Patrick762** [comment]
I'm currently working on it. Got the total_pack_voltage already. But somehow the sensors for the packs are not added yet (but they're already read)

**Comment by Patrick762** [comment]
Release 0.1 is now out and should fix this issue

**Comment by sibelle-labs** [comment]
Patrick, excelent job ! Thanks a lot !
