### ISSUE TITLE
[Bug]: AC500 + 2XB300S: Battery1+2 0% and 0V with Version 0.1.0

### ISSUE THREAD

**Issue by ItsMe00007** [Patrick762/hassio-bluetti-bt#106]
### What happened?

With Version 0.0.16 Battery1+2 showed correct % and Voltage values.

With Version 0.0.17 up to 0.0.24 it showed "unavailable"

With Version 0.1.0 "unavailable" is gone, but the % and Voltage values are 0

### What version of our software are you running?

0.1.0

### What device are you seeing the problem on?

AC500 + 2XB300S

### What bluetooth connection are you using?

ESPHome bluetooth proxy

### Have you changed the integration settings?

false

### Relevant log output

```shell
There are no error logs in the core log regarding this problem.
```
<img width="307" alt="Bildschirmfoto 2024-05-31 um 23 12 17" src="https://github.com/Patrick762/hassio-bluetti-bt/assets/126547040/3460c62d-cfcd-48d5-9b43-8f56cd297909">

Regarding "Battery Pack BMS Version": these are also not available with the Bluetti_MQTT Implementation.

UPDATE:
It seems to be a timing problem, every few minutes there are percent and voltage values shown, but for about a second, Then it changes back to 0 percent and voltage.

**Comment by sibelle-labs** [comment]
On ac300 is similar.
Showing all values correct but every few time its changes to unavailable and back.
No error on file logs.
@Patrick762 wow !!! :-)
![Screenshot_20240601_091417_Home Assistant](https://github.com/Patrick762/hassio-bluetti-bt/assets/65012538/17f27e60-ccf7-4c19-8ef6-75d496208e12)
![Screenshot_20240601_091235_Home Assistant](https://github.com/Patrick762/hassio-bluetti-bt/assets/65012538/856ab980-2e71-4d1e-94d7-9c8989acc19f)

**Comment by Patrick762** [comment]
@ItsMe00007 I'll try to ignore up to 5 invalid replies now before setting it to unavailable. This should help preventing this behavior. I'm also ignoring "0" values on pack values, those will simply be unavailable

**Comment by Patrick762** [comment]
![Screenshot 2024-06-02 at 13-50-59 Entwicklerwerkzeuge – Home Assistant](https://github.com/Patrick762/hassio-bluetti-bt/assets/80690443/9e1b0ff3-ed43-420f-a539-715332db497b)

**Comment by Patrick762** [comment]
Release 0.1.1 is now available with those modifications
