### ISSUE TITLE
repository not found

### ISSUE THREAD

**Issue by limitlessroot** [Patrick762/hassio-bluetti-bt#17]
Repository Patrick762/hassio-bluetti-bt not found

**Comment by Patrick762** [comment]
Have you used the "My" Button or added it in HACS?

**Comment by limitlessroot** [comment]
Yes

**Comment by Patrick762** [comment]
Which option of those did you use?

**Comment by Patrick762** [comment]
The button doesn't seem to work with custom repositories. You can add the repository url in HACS manually

**Comment by limitlessroot** [comment]
I see, what is the exactly url?

**Comment by Patrick762** [comment]
Installation docs: https://hacs.xyz/docs/faq/custom_repositories/

Repo URL: `https://github.com/Patrick762/hassio-bluetti-bt`

**Comment by Patrick762** [comment]
Closed because of missing feedback. Reopen if you still need help
