### ISSUE TITLE
DC Input power/current 1 and 2 (From two set of PV panels) separately

### ISSUE THREAD

**Issue by williamnavaraj** [Patrick762/hassio-bluetti-bt#20]
Thanks for this. Much appreciated.
Feature request: Any possibility to get DC Input power/current 1 and 2 (From two set of PV panels) separately? I have not dug into the code yet. If you could do, will appreciate it. Otherwise, I will try to work on this find out the feasibility and  provide a pull request when I have time.

**Comment by Patrick762** [comment]
This repo is based on the [bluetti_mqtt](https://github.com/warhammerkid/bluetti_mqtt) project. If the feature is currently not supported there, you should create a feature request there. For the AC300 f. ex. it is currently not supported ([device fields for AC300](https://github.com/warhammerkid/bluetti_mqtt/blob/main/bluetti_mqtt/core/devices/ac300.py)).
I can try to find out which fields the different PV strings are (there are some [infos on how to scan all device fields](https://github.com/warhammerkid/bluetti_mqtt/tree/main#reverse-engineering))
