### ISSUE TITLE
No stats/values for entities

### ISSUE THREAD

**Issue by JeroenVerschoor** [Patrick762/hassio-bluetti-bt#25]
I've installed the integration without issues via HACS.
It detected my Bluetti EP600 and it directly showed my EP600 device with his 36 entities. However all these entities have no stats/values, even after 24 hours.
The EP600 is running but at the moment with the inverter on 'off' state as shown within the official Bluetti app.

**Comment by Patrick762** [comment]
There currently exists a bug with non-persistent connections. Can you try again with persistent connections enabled in the integration config?
I'm already working on the bugfix in the dev branch

**Comment by JeroenVerschoor** [comment]
I've set the option to 'persistent connections' already. That didn't help to get me values from my EP600..
Something else what I can try?

**Comment by JeroenVerschoor** [comment]
- Yes, the second (bluetooth) light is blinking. The integration found my EP600 also automatically.
- It does work, I've updated the EP600 device and batteries this weekend through bluetooth
- I do not fully understand this question. I'm only connected through bluetooth with the EP600 when upgrading the device. Otherwise I use WiFi/Cloud.

Is there something I can test extra for you?

**Comment by Patrick762** [comment]
Have you already updated to 0.0.11? With the current version I get all the values. Also, the persistent connection is no longer necessary

**Comment by JeroenVerschoor** [comment]
> Have you already updated to 0.0.11? With the current version I get all the values. Also, the persistent connection is no longer necessary

I've updated to 0.0.11 and I've placed a bluetooth proxy. This combination solved my issues.
Awesome: thank you!

**Comment by Patrick762** [comment]
Closing this issue as it seems like it is solved for now
