### ISSUE TITLE
Hard Locks HA Docker

### ISSUE THREAD

**Issue by CCurvin** [Patrick762/hassio-bluetti-bt#26]
Hello,

Thanks for the integration! When I have it installed, within a few minutes Home Assistant stops responding. Nothing showing up in the logs, but it just stop responding. I have to restart the container to get it back up, and within a few minutes it stops responding again. When I remove the integration and restart the container, it's stable again, for days. Without anything different in my logs, I realize it's not very helpful information, but it is specific to this integration and repeatable/easily reproducible by just installing it, restarting the container, configuring the integration to work with a couple of EB3A batteries, and waiting a few minutes. 

"Few minutes" is vague, but it seems like it's up to ~10 minutes. I've had time to configure the integration and see a few of my EB3A batteries before it locks up. I do check the boxes to allow controlling the switches and persistent bluetooth connections.

I hope that helps.

**Comment by daniel-bergamini** [comment]
I just wanted to confirm I see the same behavior. Home Assistant running in Docker for months at a time for over a year now. I installed this Integration via HACS and the container hung in under an hour. It just stops responding. I could also get it back with a restart of the container. I uninstalled it as well when I found this bug posted.

I really appreciate the Integration, let me know if I can help troubleshoot. Thanks!

**Comment by Patrick762** [comment]
I'll look into this as soon as possible. Could you try the dev branch with persistent connection enabled?
If possible, can you export the crashlog and post the last 30 lines?

**Comment by CCurvin** [comment]
Sure thing! How do I try out the dev branch? I usually just search for the repo in HACS and install from there.

**Comment by Patrick762** [comment]
The dev branch is now live as version 0.0.11. Forgot that HACS doesn't show branches other than main

**Comment by CCurvin** [comment]
I installed 0.0.11 and it's been running for about 30 minutes so far, no lock-ups, no change in resources on the server. I am using persistent connections, and I checked the box for controls.

So, so far so good! Looks like a good update, thanks for the quick turnaround!

**Comment by CCurvin** [comment]
I'm at about 1.5 hours now, still no lock-ups. I'll check back in tomorrow, if nothing, I'll close this issue out. Thanks again.

**Comment by CCurvin** [comment]
Still working great! Thanks!
