### ISSUE TITLE
v0.0.11 connection issues on Core 2024.1.2 (working on 2023.11.3)

### ISSUE THREAD

**Issue by SupaFlav** [Patrick762/hassio-bluetti-bt#29]
Tested with OS 11.3 + Core 2023.11.3 and all appeared well, but updating to Core 2024.1.2 causes a recurring connection fault. Last error repeated thereafter every ~15s.

`2024-01-06 09:58:51.917 WARNING (MainThread) [custom_components.bluetti_bt.coordinator] Polling timed out for device XX:XX:XX:XX:XX:95 2024-01-06 09:58:51.917 WARNING (MainThread) [custom_components.bluetti_bt] You are using controls with this integration at your own risk! 2024-01-06 09:59:09.921 WARNING (MainThread) [custom_components.bluetti_bt.coordinator] Bleak error: failed to discover services, device disconnected`

Running AC200M - controls enabled, persistent connection enabled, 15s polling, 45 poll timeout, 5 max connect retries

**Comment by Patrick762** [comment]
I updated today but can't reproduce this error at the moment. I'll look into my logs tomorrow to see if I also get this error

**Comment by Patrick762** [comment]
The only bluetooth related update in the core ([habluetooth](https://github.com/Bluetooth-Devices/habluetooth/releases/tag/v2.0.2))

**Comment by SupaFlav** [comment]
I'll try again tonight but will dis/reconnect the USB adapters to the VM.  Sometimes they've gotten messed up.  All seems well today on 2023.11.3.

**Comment by SupaFlav** [comment]
Looks like it may have been an issue on my end.  Installed 2024.1.2, didn't work, shutdown and remove/reapplied virtual adapters to VM, start back up and now connected normally.
