### ISSUE TITLE
EB3A not working anymore

### ISSUE THREAD

**Issue by StormCh** [Patrick762/hassio-bluetti-bt#32]
Bluetooth connection lost every few hours. Reconnect not possible. 

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.bluetti_bt.coordinator
Source: custom_components/bluetti_bt/coordinator.py:259
Integration: Bluetti BT (documentation, issues)
First occurred: 8. Januar 2024 um 23:56:19 (1857 occurrences)
Last logged: 17:44:25

Polling timed out for device XX:XX:XX:XX:XX:C6
```

**Comment by Patrick762** [comment]
What integration settings do you use? Defaults?
You can see the settings under "Konfigurieren" in the integration settings

**Comment by StormCh** [comment]
Defaultsettings
![image](https://github.com/Patrick762/hassio-bluetti-bt/assets/4211645/7daf26b5-0805-422d-ad54-902fad8c8c79)

**Comment by Patrick762** [comment]
Have you already updated to 0.0.11? This version contains some bugfixes for connection problems.
If yes, try to disable the persistent connection ("Dauerhafte Verbindung")

**Comment by StormCh** [comment]
This is Version 0.0.11. I'll give it a try "Dauerhafte Verbindung"

**Comment by Patrick762** [comment]
Seems like this issue is solved
