### ISSUE TITLE
Trying to read from my AC300

### ISSUE THREAD

**Issue by DougKremer** [Patrick762/hassio-bluetti-bt#33]
Fresh Pi with bluetooth dongle.  The system sees my AC300, and EB3A, and prompts me to configure them.  it won't pull data,  logs are filled with this:

2024-01-27 11:55:10.872 WARNING (MainThread) [custom_components.bluetti_bt.sensor] Data from coordinator is None. Skipping update for ac3002XXXXXXXXXXbattery_pack_4_voltage
2024-01-27 11:55:10.872 WARNING (MainThread) [custom_components.bluetti_bt.sensor] Data from coordinator is None. Skipping update for ac3002XXXXXXXXXXbattery_pack_4_percent
2024-01-27 11:55:30.864 WARNING (MainThread) [custom_components.bluetti_bt.coordinator] Bleak error: No backend with an available connection slot that can reach address 00:15:XX:XX:XX:XX was found

I also get one of these on boot:

This error originated from a custom integration.

Logger: mqtt
Source: custom_components/bluetti_bt/const.py:3
Integration: Bluetti BT (documentation, issues)
First occurred: 11:46:50 AM (1 occurrences)
Last logged: 11:46:50 AM

We renamed asyncio-mqtt to aiomqtt and released a version 1.0.0 in the process. This is the last release under the asyncio-mqtt name. You can find the new repository at https://github.com/sbtinstruments/aiomqtt

**Comment by Patrick762** [comment]
Which version of the integration are you using?
Can you try to switch between persistent and non persistent mode (in the configuration of the integration)?

The part you see on boot is an issue caused by the bluetti_mqtt library this integration uses. This can be ignored.

FYI: I edited your issue to hide your device MAC.

**Comment by DougKremer** [comment]
I started on .11, which is where the errors are from, then rolled back to .10, no log errors, but no data just the same. Persistence switch no change. ~DougkOn Jan 27, 2024, at 1:33 PM, Patrick762 ***@***.***> wrote:﻿
Which version of the integration are you using?
Can you try to switch between persistent and non persistent mode (in the configuration of the integration)?
The part you see on boot is an issue caused by the bluetti_mqtt library this integration uses. This can be ignored.
FYI: I edited your issue to hide your device MAC.

**Comment by DougKremer** [comment]
I tried a different BT adapter tonight, same outcome.

**Comment by DougKremer** [comment]
Fourth bluetooth dongle from the HomeAssistant approved list,  DATA!
~closing.
