### ISSUE TITLE
[Bug]: AC500+b300s - only one battery appears used

### ISSUE THREAD

**Issue by viliusdidit** [Patrick762/hassio-bluetti-bt#35]
### What happened?

I noticed a mismatch between bluetti app and hassio: first two batteries are always reported at 100% while the 3rd one fluctuates between 75-87, voltage has similar pattern.
sensor.blue_ac500_battery_pack_2_percent
sensor.blue_ac500_battery_pack_1_voltage
sensor.blue_ac500_battery_pack_2_status - unknown

Minor issue as total seems to be fine:
sensor.blue_ac500_total_battery_percent

I'm leaning towards this being untested/bug with ac500 here. It is possible bluetti app is misreporting as well but data looks more realistic.

Let me know/point me how I can send you better debug info/tests.

cheers

![Screenshot_2024-01-30-03-21-58-12_c3a231c25ed346e59462e84656a70e50](https://github.com/Patrick762/hassio-bluetti-bt/assets/1178578/58dbd436-479f-4434-8d45-609655d55ff2)

![Screenshot_2024-01-30-03-23-32-89_f1c106e665bed24c8e00c9069bf9ec39](https://github.com/Patrick762/hassio-bluetti-bt/assets/1178578/4ebd167b-2a9d-47e8-9c61-82deec6713d1)

### Version

0.0.11

### What device are you seeing the problem on?

AC500

### What bluetooth connection are you using?

USB dongle

### Have you changed the integration settings?

false

**Comment by Patrick762** [comment]
The AC500 is included from [bluetti_mqtt](https://github.com/warhammerkid/bluetti_mqtt), so the bug is most likely caused there.

**Comment by bobthebuilder4711** [comment]
I'm using bluetti_mqtt with an AC500 and 4x B300S and while the percentages can start to drift from each other when you don't use enough power or charge to 100% from time to time, that doesn't mean that the voltages should be so varying as shown here.

For example my total percentage is 30%. Two packs are reporting 1%, the other two are reporting 60%. But all of them are reporting a voltage of 53.1V.

And the LEDs on the B300Ss themselves show these different percentages too.

But while that is bad guestimating on bluetti's part in my case, I doubt that it's the same here.

**Comment by Patrick762** [comment]
Can you test the beta release 0.0.16? The data should show up in this release

**Comment by viliusdidit** [comment]
latest DSP/ARM version with latest integration version works fine.
