### ISSUE TITLE
No power_off button?

### ISSUE THREAD

**Issue by renarena** [Patrick762/hassio-bluetti-bt#47]
I miss the power off button i am used to from bluetti to mqtt.

**Comment by Patrick762** [comment]
I didn't add it yet because I couldn't test it with my AC300

**Comment by Patrick762** [comment]
I added it in PR #48, but I can't test it

**Comment by Patrick762** [comment]
Integrated as a switch in version 0.0.20

**Comment by renarena** [comment]
It works.
In bluetti mqtt integration it is a button, not a switch. 
In hardware, its a button too.
The 3 switches are always unknown, as is the power off sensor.
3x battery_pack_1 sensors , Internal AC Frequency and screen sleep mode sensor are unknown too.

**Comment by Patrick762** [comment]
Which powerstation are you using?

**Comment by renarena** [comment]
AC200M

**Comment by GodnessHimself** [comment]
I'm using the AC200M. How I can control AC / DC switch + Display on Time?

**Comment by Patrick762** [comment]
@GodnessHimself To enable controls, use the "Configure" ("Konfigurieren" in German) button of the device in Home Assistant
