### ISSUE TITLE
[Bug]: Documentation

### ISSUE THREAD

**Issue by Tokynet** [Patrick762/hassio-bluetti-bt#57]
### What happened?

Bought a Bluetti AC300 mainly because of the HA integration.
Sadly, i'm not sure where to start, there is no documentation on how to use this integration.

FWIW, I try to stay no-more than 1 HA version behind. 

I have a bluetooth dongle on my HA (Blue) device. Besides installing this integration through HACS and having a bluetooth dongle, what else do I need to do?

More details:

I can see the bluetti-bt integration when I click on "Add integration" from the settings menu.
When I click it, it just has a drop-down full of MAC address which I assume are bluetooth MACs.
I installed an app on my android device to scan MAC addresses, so now I know the MAC for the AC300, but I can't find its MAC in the values listed on the dropdown.
I assume I'm missing a step somewhere.

Thanks in advance!

### Version

0.0.17

### What device are you seeing the problem on?

AC300

### What bluetooth connection are you using?

USB dongle

### Have you changed the integration settings?

false

**Comment by Patrick762** [comment]
Do you have an ESP32 instead of the Bluetooth USB Dongle to use as [Bluetooth proxy](https://esphome.io/projects/?type=bluetooth)? Some USB Dongles [might not work with Home Assistant](https://www.home-assistant.io/integrations/bluetooth/) (in my case only 1 out of 4 worked as expected).
It could also be too far away from the Bluetooth dongle (in this case you can use the Bluetooth proxy).

The AC300 should be detected without adding it manually (you should see it on your Integrations page at the top).

**Comment by Patrick762** [comment]
Also, thanks for sponsoring this project

**Comment by Tokynet** [comment]
Thanks for the reply :) 
I believe I have a few of these (EST-PoE-32) left around.

But If I go this route, I would have to (re)add and configure MQTT to my HA install, correct?

I had added MQTT awhile back but its not really in-use since the component I used it for was moved behind a pay-wall.

**Comment by Patrick762** [comment]
You don't need MQTT for this integration. It uses the built in Bluetooth Manager of Home Assistant

**Comment by Tokynet** [comment]
Got it.
I did try to configure the device I mentioned above (EST-PoE-32) but failed to get it configured. My main block right now is the device is PoE so its "wired" but I can't get it to DHCP an IP address at all.

I will close this issue, since my "issue" is no longer with your code/component.
Thanks for your help.
