### ISSUE TITLE
[Feature Request]: Add compatibility to energy Dashboard

### ISSUE THREAD

**Issue by GammaPotato** [Patrick762/hassio-bluetti-bt#69]
yea.. the name above says is "Add compatibility to energy Dashboard". its will be nice to see how much energy got used, stored and generated if the is an solar panel. is it possible to add?

**Comment by GammaPotato** [comment]
I have the EB3A. Is it possible make it for this possible?

**Comment by ItsMe00007** [comment]
I added the following manually to my configuration.yaml to convert the power information from my AC500 into energy information to be able to include it into the energy panel.

Just use your sensor details, then you can configure the PV Part of the energy panel.
Reload YAML or restart HA after updating the configuration.yaml.
It could take some time until you see the new ENERGY sensors in the Overview.

   # AC500 Convert Power to Energy
  - platform: integration
    source: sensor.ac5002241000084770_dc_input_power
    name: AC500_PV_IN_Energy
    unique_id: AC500_PV_IN_Energy
    unit_prefix: k
    unit_time: h
    round: 2
  - platform: integration
    source: sensor.ac5002241000084770_ac_output_power
    name: AC500_AC_OUT_Energy
    unique_id: AC500_AC_OUT_Energy
    unit_prefix: k
    unit_time: h
    round: 2

**Comment by GammaPotato** [comment]
this is the "riemann helper" right?

**Comment by GammaPotato** [comment]
@Patrick762 pls add the requested function. the Riemann helper didnt work correct.

**Comment by Patrick762** [comment]
I'll look into it as soon as I find some more time. Shouldn't be too difficult

**Comment by ItsMe00007** [comment]
> this is the "riemann helper" right?

Yes, this is the Riemann helper .

 What did not work correct ?

**Comment by Patrick762** [comment]
Riemann helper often doesn't work. I also have problems with the helper when measuring water flow

**Comment by GammaPotato** [comment]
> > this is the "riemann helper" right?
> 
> Yes, this is the Riemann helper .
> 
>  What did not work correct ?

I charged the EB3A With my solar 1,3 kwh(riemann says that) Then used it for 2 hours with 9 watts. Riemann says i used 4,56 kwh? That cant be possible
