### ISSUE TITLE
[Bug]: AC500 + 2xB300S: all Battery Infos are "unknown", "DC Input 1" missing

### ISSUE THREAD

**Issue by ItsMe00007** [Patrick762/hassio-bluetti-bt#70]
### What happened?

I just moved from Bluetti_MQTT Integration on a Raspberry PI to your integration. Thanks for all the effort.

I got all the infos from my AC500 except:
1.  all battery infos are missing except  "Total Battery Percent".
2. "DC Input 1" is missing

With the  Bluetti_MQTT  0.11 I got the battery percent infos for both batteries and also for "DC Input 1" (for PV Input 1, additional to "DC Input" for complete PV Input).

<img width="293" alt="Battery Info1" src="https://github.com/Patrick762/hassio-bluetti-bt/assets/126547040/798b21ea-96bc-4bcd-9222-3585323c3bcf">
<img width="293" alt="Battery Info2" src="https://github.com/Patrick762/hassio-bluetti-bt/assets/126547040/6e8815c8-2774-4867-af04-8d5f8884c3c4">

### Version

0.0.11

### What device are you seeing the problem on?

AC500

### What bluetooth connection are you using?

USB dongle

### Have you changed the integration settings?

Yes (Please write down the changed settings in the next step)

### Integration settings (if you changed them)

```text
Use Controls changed to "Enabled" and Debug changed to "Enabled"
```

### Relevant log output

```shell
This error originated from a custom integration.

Logger: custom_components.bluetti_bt.sensor
Source: custom_components/bluetti_bt/sensor.py:163
Integration: Bluetti BT (documentation, issues)
First occurred: 15:33:21 (6230 occurrences)
Last logged: 21:14:18

No data for available for (pack_voltage1)
No data for available for (pack_battery_percent1)
No data for available for (pack_status2)
No data for available for (pack_voltage2)
No data for available for (pack_battery_percent2)
```

**Comment by ItsMe00007** [comment]
To compare it I installed the Bluetti_MQTT 0.15 Version on my Raspberry PI and I get the Battery1+2 Percent+Voltage and the "DC Input 1 Power/Current/Voltage" 

<img width="475" alt="Battery Info MQTT Integration1" src="https://github.com/Patrick762/hassio-bluetti-bt/assets/126547040/c936a7bd-bee1-4580-9392-646d5f5a1313">
<img width="465" alt="Battery Info MQTT Integration2" src="https://github.com/Patrick762/hassio-bluetti-bt/assets/126547040/d5fb01c1-c4d6-421c-91f3-13be0691e7fa">

**Comment by ItsMe00007** [comment]
The main info about the missing battery information has been solved.
Therefore i close the bug.
But it would be great if you can add these 3 sensors which are available in the implementation of warhammerkid:
"DC Input Power 1"
"DC Input Voltage 1"
"DC Input Current 1

Thanks

**Comment by Patrick762** [comment]
@ItsMe00007 I looked at the bluetti_mqtt code but couldn't find "DC Input Power 1" in the AC500 config. Did you mean another powerstation? Or did you rename them?

**Comment by ItsMe00007** [comment]
> @ItsMe00007 I looked at the bluetti_mqtt code but couldn't find "DC Input Power 1" in the AC500 config. Did you mean another powerstation? Or did you rename them?

No, I didn't rename it. All the Sensor names are original from the implementation.

But I also haven't found it in the origin AC500 config file, I guess that the ACxx Files only show what is different to others and the "DC Input Power 1" and "DC Input Voltage  1" are in a file which is common to more devices.

This is how it looks with bluetti_MQTT:
<img width="315" alt="Bildschirmfoto 2024-03-16 um 17 02 32" src="https://github.com/Patrick762/hassio-bluetti-bt/assets/126547040/2d8cd00f-65e5-4188-a946-3be0512deda4">

**Comment by Patrick762** [comment]
If I understand it correctly, it should be available as entity, but as "Internal DC Input Power"

**Comment by Patrick762** [comment]
I don't understand why this is renamed in the mqtt_client file, but it should already be there

**Comment by ItsMe00007** [comment]
BTW: I just discovered that "Internal Current Sensor 3" and "Internal Power Sensor 3" are also missing in your integration compared to the Bluetti_MQTT.

**Comment by Patrick762** [comment]
Those are already defined here:
https://github.com/Patrick762/hassio-bluetti-bt/blob/dc3aaf92e142302ca87a4c7c08184406b9992c55/custom_components/bluetti_bt/bluetti_bt_lib/devices/ac500.py#L24

If I have some time tomorrow I'll test the latest version on an AC300 (very similar)

**Comment by ItsMe00007** [comment]
> If I understand it correctly, it should be available as entity, but as "Internal DC Input Power"

Ah ok, I'll check it tomorrow when the PV starts. The AC500 has got 2 PV Inputs and up to now only the PV1 DC Input was found by warrhammerkid.
But in the current Bluetti App it is now possible to click on the PV icon and it shows PV1 Power+Voltage as well PV2 Power+Voltage.
So I guess somebody will find the modbus register for the second PV Input.

The it makes sense to add a 1 to  the current "Internal DC Input Power" to be prepared for a "Internal DC Input ....  2"

**Comment by ItsMe00007** [comment]
Scaling Factor is still wrong for internal dc input:
Voltage: should be 90,1 instead of 901
Power: should be 300 instead of 30
