### ISSUE TITLE
[Bug]: All entities 'unknown' after reinstallation no entities found

### ISSUE THREAD

**Issue by JeroenVerschoor** [Patrick762/hassio-bluetti-bt#79]
### What happened?

I had this add-on working for a while, but suddenly the situation arose again (after an update) in which entities were given the status 'unknown'.
I've removed my configuration, restarted my EP600, restarted HA and tried to connect.
The device was now auto discovered (though an ESPhome bluetooth proxy). After selection the auto discovered device the add-on throws me the following error: 'setup failed, will try again' and 'no devices or entities found'.

### Version

0.0.17

### What device are you seeing the problem on?

EP500

### What bluetooth connection are you using?

ESPHome bluetooth proxy

### Have you changed the integration settings?

false

### Integration settings (if you changed them)

```text
It's an EP600, but this device was not selectable in the above dropdown.
Using version 0.0.21 (which was not selectable in the above dropdown).
```

### Relevant log output

```shell
Error setting up entry U2246000761042 for bluetti_bt
13:06:29 - (FOUT) config_entries.py

Bleak error: No backend with an available connection slot that can reach address: E0:5a:1B:45:5C:45 was found
13:05:30 - (FOUT) Bluetti BT  (custom integration) - message first came at 13:05:03 and appears 46 times

Polling timed out
13:05:30 - (FOUT) Bluetti BT  (custom integration) - message first came at 13:05:03 and appears 3 times
```

**Comment by Patrick762** [comment]
Have you tried restarting the Esphome Bluetooth Proxy? Had a similar problem recently. After restarting HA it seems those proxies don't reconnect correctly

**Comment by JeroenVerschoor** [comment]
Thank you Patrick, that solved my issue 👍.

**Comment by GodnessHimself** [comment]
how can I use a ESP Bluetooth Proxy? I tried this with the ESP proxy, but no connection could be established? So I use this: https://github.com/mariolukas/Bluetti_ESP32_Bridge 
Unfortunately, I am missing some setting options and data :(

**Comment by Patrick762** [comment]
Closing because last question isn't related to original issue
