### ISSUE TITLE
EB3A feedback and controls

### ISSUE THREAD

**Issue by matthewhadley** [Patrick762/hassio-bluetti-bt#8]
Hello,

Thanks for working on this component. It seems to have detected the majority of sensors on my EB3A:

<img width="320" alt="Screenshot 2023-08-17 at 16 27 30" src="https://github.com/Patrick762/hassio-bluetti-bt/assets/36013/63216852-0065-4725-b1ae-10b1c6f28829">

Do you have plans to support any controls of Bluetti devices? (turn on/off etc). I am currently using ESP32 devices with https://github.com/mariolukas/Bluetti_ESP32_Bridge to do this (over MQTT -> ESP32 device -> bluetooth -> Bluetti).

**Comment by Patrick762** [comment]
I thought about adding them, but they could cause issues if bluetti changes the api in the future.
Maybe I'll add them, but add an option (for each devide) to enable them at your own risk.

**Comment by SupaFlav** [comment]
Hello, seconded for some toggle controls.  I'm specifically looking to toggle the AC & DC output.

Thanks for all you hard work!

**Comment by Patrick762** [comment]
The switches for AC and DC Outputs are now working on my AC300.
I'll create the release today or tomorrow (have to fix the enum bug too).

**Comment by Patrick762** [comment]
New release is now available: 0.0.9
