### ISSUE TITLE
[Bug]: integration freezes

### ISSUE THREAD

**Issue by GodnessHimself** [Patrick762/hassio-bluetti-bt#81]
### What happened?

The integration freezes after a certain time and can no longer be started and does not display any current values. 
Is the problem known?

### Version

0.0.11

### What device are you seeing the problem on?

AC200M

### What bluetooth connection are you using?

ESPHome bluetooth proxy

### Have you changed the integration settings?

false

**Comment by Patrick762** [comment]
Have you tried restarting your BT Proxy?

**Comment by GodnessHimself** [comment]
yes. yesterday. after 5h the it freeze again. after the restart it runs without problems.
How can I install the beta versions?

**Comment by GodnessHimself** [comment]
<img width="562" alt="Bildschirmfoto 2024-03-29 um 19 53 15" src="https://github.com/Patrick762/hassio-bluetti-bt/assets/96915748/eb619b41-6cb8-4009-bbac-f0b2cea3e892">

Today I had the same problem. 
The Bluetti was set to "connect" (connected) but the HA showed "unknown" for all values
After restarting the ESP32 it works again.
That's annoying :( Is there anything else I can do? Maybe it's not the Bluetti tool?

**Comment by Patrick762** [comment]
Do you use other bluetooth devices with Home Assistant? I have multiple which all have this problem. It most likely is a bug in the proxy itself (have to test a bit more to confirm this).

**Comment by Patrick762** [comment]
You can install the beta versions if you activate them in HACS. Then select a version before selecting and downloading the latest beta version

**Comment by Patrick762** [comment]
Closing issue because of missing response
