### ISSUE TITLE
Bluetti EP760  Home Assistant intigrieren

### ISSUE THREAD

**Issue by Kankea** [Patrick762/hassio-bluetti-bt#97]
Hallo Patrick,

könntest du mir Bitte Helfen?
 eventuell  kurz beschreiben was ich alles machen muss um meine ep760 zu intigrieren.

Habe schon hassio-bluetti-bt in Hacs installiert aber komme nicht weiter.

Ich muss ja irgendwie eine Bluetooth  verbindung herstellen und den Sensor einbinden, weiß leider nicht wie es geht.

**Comment by Fridgeir-9** [comment]
Hi Kankea, ich stand vor dem gleichen Problem. Aber Du kannst in HACS beim Hinzufügen anstelle des 'main' channels den 'dev' channel wählen. Dort hat Patrick bereits Neuerungen drin -> https://github.com/Patrick762/hassio-bluetti-bt/tree/dev

unter anderem die EP760
Ich habe die AC180 und erhalte damit zumindest Basisdaten wie die Prozentabgabe des Akkustands

**Comment by Kankea** [comment]
Hallo Fridgeir-9,  

Danke für deine Antwort, Ich versuche verkrampft zu finden wo man in HACS einstellen kann den dev Channel.

Würde mich sehr freuen wenn du mir in groben schritten erklären könntest, wie du es zum laufen gebracht hast. Benutzt du ein Bluethoot Dongel oder ein Bluethoot Proxy?

**Comment by Patrick762** [comment]
![Screenshot 2024-04-28 at 20-47-02 HACS – Home Assistant](https://github.com/Patrick762/hassio-bluetti-bt/assets/80690443/7772844b-1422-42bc-b26f-51382ae051fe)

**Comment by Fridgeir-9** [comment]
einmal in HACS die Integration löschen und neu herunterladen, so wie es auf dem Screenshot von Patrick ist

**Comment by Kankea** [comment]
Vielen lieben großen Dank euch beiden, ich nutze so sellten die Funktionen mit Hacs aber das mit dem erneut herunterladen hat mich weitergebracht.

Jetzt habe ich die 0.0.23 installiert und er hat mein EP760 Bluethoot automatisch erkannt.

Und ich dachte ich muss noch irgend eine config anpassen, mac von Bluethott eintragen u.s.w.  das war ja wirklich leicht.

@Patrick762 Du Patrick zur Zeit wird nur der Battary status angezeigt, wirst du mit der Zeit noch andere Sensoren einbinden?

Wenn du etwas von der EP760 brauchst und ich dir irgendwie Helfen kann dann sag gerne bescheid.

Noch mals vielen lieben Dank an euch beiden.

**Comment by Youchoum** [comment]
Guten Morgen ,
Ich besitze ebenfalls einen EP760 und bin sehr an der Weiterentwicklung der Kompatibilität dieser Integration interessiert.
Derzeit findet Bluetti_BT für mich das BLUETOOHT des EP760, aber ein Konfigurationsfehler bleibt bestehen und es kommen keine Informationen zurück, selbst wenn auf den Beta-Kanal 0.0.23 umgestellt wird
Wenn mich jemand aufklären könnte, wäre das großartig.

**Comment by Kankea** [comment]
Hallo Youchoum,

bist du weiter gekommen?
Wie hast du dein Bluetooth  an HA angebunden?

Ich hab es per USB Dongel gemacht, die Bluetooth integration installiert und auf die 0.0.23 aktualisiert und HA neu gestartet und dann lief es bei mir.

**Comment by Youchoum** [comment]
hallo Kankea,

Vielen Dank für die Antwort, ich habe es endlich geschafft, meinen EP760 dazu zu bringen, mit HA zu kommunizieren.
Ich habe einen BT-Proxy mit einem ESP32 eingerichtet.

Wie viele Einheiten haben Sie?

Ich für meinen Teil habe nur die gesamte tägliche Solarproduktion und den Batterieprozentsatz

**Comment by Kankea** [comment]
Mit Einheiten meinst du in HA die Identitäten, Sensoren? 

Total Battery Percent  87 %
Total Power Generation  399,9 kWh

Ich hoffe das es mit dem nächsten Update von Patrick mehr gibt.

Sag mal hast du deine PV-Module direkt an die EP760 angeschlossen?

**Comment by Youchoum** [comment]
Ja, das sind die Identitäten.
Ich hoffe auch, dass später noch mehr kommt.

Ja, meine Panels sind direkt an den MPPT EP760 angeschlossen

**Comment by Kankea** [comment]
Wie viele Module hast du pro String Angeschlossen?
Hast du auch zusätzlichen Blitzschutz für die Pv_Module?

**Comment by Youchoum** [comment]
Ich habe 2 Strings mit 6 Panels (440 Wc), die in Reihe geschaltet sind (mindestens 150 V für den MPPT-Eingang).
Ich verwende die PV1- und PV2-Eingänge am EP und habe eine Erdungsleitung erstellt, die von den Befestigungsschienen zum Erdungsanschluss von PV1 führt

**Comment by Kankea** [comment]
Vielen Dank für deine Antwort, hab noch eine Frage. Wie verhält sich bei dir wlan, APP und die Cloud? 

Ich hab immer wieder das Problem das meine Verbindung zur Cloud nicht aufgebaut werden kann, erst nach dem reset der wlan box.

kennst du das Problem?

**Comment by Youchoum** [comment]
Gern geschehen, es ist gut, mit jemand anderem über dieses System sprechen zu können, da ich im Internet wirklich sehr wenig Thema zum EP760 finde.
Meines Wissens nach gab es kein Netzwerkproblem. Das einzige Problem, das ich hatte, war, dass ich trotz Neustart der App, Leeren des Caches und Neustart des EP drei Tage hintereinander keine Verbindung herstellen konnte. Dies hat jedoch nichts geändert

**Comment by Kankea** [comment]
Ich hab bei mir den Caches gelösch, die App neu installiert alles ohne erfolg bis ich die kleine Taste an dem wlan Modul (RST) gedrückt hatte.  Dann hat er sich als ob nichts wäre sofort mit der cloud verbunden.

**Comment by Youchoum** [comment]
Ja, die App ist zunächst nicht sehr intuitiv und die Bedienung wurde durch die neuesten Updates deutlich verbessert.

Sie legen Ihren S.O.C. zwischen „wie viel“ und „wie viel“ fest.

Ich würde mir wünschen, dass die Solarenergie bevorzugt wird, sodass die Solarenergie stoppt, wenn die Batterie 100 % erreicht hat, und wieder startet, sobald die Batterie wieder 99 % erreicht hat

**Comment by Patrick762** [comment]
Bitte für Nachrichten die Discussions oder den Discord Server https://discord.gg/7RE4eCET nutzen

**Comment by Kankea** [comment]
Moin, Ich weiß wie man bei dem EP760 mehr Daten auslesen kann.

Einfach die EP760.py bearbeiten und von der EP600.py übernehmen.

/homeassistant/custom_components/bluetti_bt/bluetti_bt_lib/devices/ep760.py
