### ISSUE TITLE
AC500: Version up to 0.0.23: Scaling wrong for three "Internal DC Input" entities

### ISSUE THREAD

**Issue by ItsMe00007** [Patrick762/hassio-bluetti-bt#98]
Hi,
the scaling for the Internal DC Input is still wrong:
<img width="301" alt="Bildschirmfoto 2024-05-06 um 07 54 37" src="https://github.com/Patrick762/hassio-bluetti-bt/assets/126547040/2812e442-e0b7-400c-a15a-3caf02f68c7b">

"Internal DC Input Current": x10, should be 2,2A instead of 0,22A
"Internal DC Input Power": x10, should be 225W instead of 22,5W
"Internal DC Input Voltage": /10, should be 101,5V instead of 1015V

**Comment by sibelle-labs** [comment]
Hi,
Same on AC300 Series.
Thanks a lot

**Comment by Patrick762** [comment]
0.0.24 should fix the voltage. I'll do the other values tomorrow when the sun is up

**Comment by Patrick762** [comment]
It seems to me like those values are the separate solar strings.

For example I got:
- DC Input 150W
- Internal DC Input Power 72W

The big question now is, which of the two strings is this and where can we find the other one?

**Comment by Patrick762** [comment]
@ItsMe00007 Which string are you using currently?

**Comment by Patrick762** [comment]
Release 0.1 is now out and should fix this issue

**Comment by ItsMe00007** [comment]
> @ItsMe00007 Which string are you using currently?

I have one string with 3x375W modules and one string with 3x405W modules.

If I click on "PV" in the App I can see both PV Input's and DC1 matches the Internal DC Input.
But up to now nobody has found the DC2 (PV2) registers.

I have tried to create debug outputs during the time I press on the "PV" button, but if I connect the App via Bluetooth then I cannot connect via Bluetooth from the HA.
And if i use the App via the Bluetti Server, then I have no debug Log's from the time I press on the "PV" button.

**Comment by ItsMe00007** [comment]
Problem solved with 0.1.
Great Job Patrick

**Comment by ItsMe00007** [comment]
Problem solved with 0.1.
